# Generated by Django 4.0.4 on 2022-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(unique=True, verbose_name='employee_number'),
        ),
    ]
