# Generated by Django 4.0.4 on 2022-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_employee_number_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=5, unique=True, verbose_name='employee number'),
        ),
    ]
