# Generated by Django 4.0.4 on 2022-09-21 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.IntegerField()),
                ('date', models.DateField(blank=True, default=datetime.date(2022, 9, 21))),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.table')),
            ],
        ),
    ]
